version: "3"

services:
  sonarqube:
    image: sonarqube:9.0.1-community
    expose:
      - 9018
    ports:
      - "9018:9000"
    networks:
      - sonarnet
    environment:
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
      -sonarqube_results:/var/lib/jenkins/workspace/task4-docker-compose/target/hello-world-docker-1.0-SNAPSHOT.jar

  db:
    image: postgres:13.4
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
  java:
    container_name: loginJava
    image: openjdk:7
    depends_on:
      - db
    volumes:
      - /var/lib/jenkins/workspace/docker/target:/usr/src/myapp 
    working_dir: /usr/src/myapp
    command: bash -c "java -jar hello-world-docker-1.0-SNAPSHOT.jar"
networks:
  sonarnet:

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data:
